export default {
    SET_ACTIVE_PLAYER_ID: 'SET_ACTIVE_PLAYER_ID',
    SET_ACTIVE_PLAYER_INDEX: 'SET_ACTIVE_PLAYER_INDEX',
    SELECT_NEXT_ACTIVE_PLAYER: 'SELECT_NEXT_ACTIVE_PLAYER',
    ATTACK: 'ATTACK',
    SUPPORT: 'SUPPORT',
    APPLY_DAMAGE: 'APPLY_DAMAGE',
    APPLY_HEAL: 'APPLY_HEAL',
}